//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var CommonModel_ttypes = require('./CommonModel_types')
var BizAccountInfoThriftServiceModel_ttypes = require('./BizAccountInfoThriftServiceModel_types')
var BizAccountPhoneThriftServiceModel_ttypes = require('./BizAccountPhoneThriftServiceModel_types')


var ttypes = require('./BizAccountPhoneInfoThriftService_types');
//HELPER FUNCTIONS AND STRUCTURES

var BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_args.prototype = {};
BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case -1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountInfoThriftServiceModel_ttypes.GetBizAccPhoneByIdsReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, -1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result.prototype = {};
BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountInfoThriftServiceModel_ttypes.GetBizAccPhoneResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_args.prototype = {};
BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case -1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountInfoThriftServiceModel_ttypes.GetBizAccPhoneByDpIdsReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, -1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result.prototype = {};
BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountInfoThriftServiceModel_ttypes.GetBizAccPhoneResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_args.prototype = {};
BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountInfoThriftServiceModel_ttypes.GetBizAccPhoneByIdsAndTokenReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result.prototype = {};
BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountInfoThriftServiceModel_ttypes.GetBizAccPhoneResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_args.prototype = {};
BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountInfoThriftServiceModel_ttypes.GetBizAccPhoneByDpIdsAndTokenReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result.prototype = {};
BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountInfoThriftServiceModel_ttypes.GetBizAccPhoneResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_args.prototype = {};
BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case -1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountPhoneThriftServiceModel_ttypes.BizAcctIdsReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, -1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result.prototype = {};
BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountPhoneThriftServiceModel_ttypes.BizAcctPhoneResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountPhoneInfoThriftServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
BizAccountPhoneInfoThriftServiceClient.prototype = {};
BizAccountPhoneInfoThriftServiceClient.prototype.seqid = function() { return this._seqid; }
BizAccountPhoneInfoThriftServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
BizAccountPhoneInfoThriftServiceClient.prototype.getBizAccPhoneByIds = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getBizAccPhoneByIds(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getBizAccPhoneByIds(req);
  }
};

BizAccountPhoneInfoThriftServiceClient.prototype.send_getBizAccPhoneByIds = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getBizAccPhoneByIds', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountPhoneInfoThriftServiceClient.prototype.recv_getBizAccPhoneByIds = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getBizAccPhoneByIds failed: unknown result');
};
BizAccountPhoneInfoThriftServiceClient.prototype.getBizAccPhoneByDpIds = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getBizAccPhoneByDpIds(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getBizAccPhoneByDpIds(req);
  }
};

BizAccountPhoneInfoThriftServiceClient.prototype.send_getBizAccPhoneByDpIds = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getBizAccPhoneByDpIds', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountPhoneInfoThriftServiceClient.prototype.recv_getBizAccPhoneByDpIds = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getBizAccPhoneByDpIds failed: unknown result');
};
BizAccountPhoneInfoThriftServiceClient.prototype.getBizAccPhoneByIdsV2 = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getBizAccPhoneByIdsV2(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getBizAccPhoneByIdsV2(req);
  }
};

BizAccountPhoneInfoThriftServiceClient.prototype.send_getBizAccPhoneByIdsV2 = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getBizAccPhoneByIdsV2', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountPhoneInfoThriftServiceClient.prototype.recv_getBizAccPhoneByIdsV2 = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getBizAccPhoneByIdsV2 failed: unknown result');
};
BizAccountPhoneInfoThriftServiceClient.prototype.getBizAccPhoneByDpIdsV2 = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getBizAccPhoneByDpIdsV2(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getBizAccPhoneByDpIdsV2(req);
  }
};

BizAccountPhoneInfoThriftServiceClient.prototype.send_getBizAccPhoneByDpIdsV2 = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getBizAccPhoneByDpIdsV2', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountPhoneInfoThriftServiceClient.prototype.recv_getBizAccPhoneByDpIdsV2 = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getBizAccPhoneByDpIdsV2 failed: unknown result');
};
BizAccountPhoneInfoThriftServiceClient.prototype.getBizAcctPhoneByIds = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getBizAcctPhoneByIds(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getBizAcctPhoneByIds(req);
  }
};

BizAccountPhoneInfoThriftServiceClient.prototype.send_getBizAcctPhoneByIds = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getBizAcctPhoneByIds', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountPhoneInfoThriftServiceClient.prototype.recv_getBizAcctPhoneByIds = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getBizAcctPhoneByIds failed: unknown result');
};
var BizAccountPhoneInfoThriftServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
BizAccountPhoneInfoThriftServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

BizAccountPhoneInfoThriftServiceProcessor.prototype.process_getBizAccPhoneByIds = function(seqid, input, output) {
  var args = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getBizAccPhoneByIds.length === 1) {
    Q.fcall(this._handler.getBizAccPhoneByIds, args.req)
      .then(function(result) {
        var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result({success: result});
        output.writeMessageBegin("getBizAccPhoneByIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result(err);
        output.writeMessageBegin("getBizAccPhoneByIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getBizAccPhoneByIds(args.req,  function (err, result) {
      var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIds_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getBizAccPhoneByIds", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountPhoneInfoThriftServiceProcessor.prototype.process_getBizAccPhoneByDpIds = function(seqid, input, output) {
  var args = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getBizAccPhoneByDpIds.length === 1) {
    Q.fcall(this._handler.getBizAccPhoneByDpIds, args.req)
      .then(function(result) {
        var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result({success: result});
        output.writeMessageBegin("getBizAccPhoneByDpIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result(err);
        output.writeMessageBegin("getBizAccPhoneByDpIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getBizAccPhoneByDpIds(args.req,  function (err, result) {
      var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIds_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getBizAccPhoneByDpIds", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountPhoneInfoThriftServiceProcessor.prototype.process_getBizAccPhoneByIdsV2 = function(seqid, input, output) {
  var args = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getBizAccPhoneByIdsV2.length === 1) {
    Q.fcall(this._handler.getBizAccPhoneByIdsV2, args.req)
      .then(function(result) {
        var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result({success: result});
        output.writeMessageBegin("getBizAccPhoneByIdsV2", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result(err);
        output.writeMessageBegin("getBizAccPhoneByIdsV2", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getBizAccPhoneByIdsV2(args.req,  function (err, result) {
      var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByIdsV2_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getBizAccPhoneByIdsV2", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountPhoneInfoThriftServiceProcessor.prototype.process_getBizAccPhoneByDpIdsV2 = function(seqid, input, output) {
  var args = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getBizAccPhoneByDpIdsV2.length === 1) {
    Q.fcall(this._handler.getBizAccPhoneByDpIdsV2, args.req)
      .then(function(result) {
        var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result({success: result});
        output.writeMessageBegin("getBizAccPhoneByDpIdsV2", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result(err);
        output.writeMessageBegin("getBizAccPhoneByDpIdsV2", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getBizAccPhoneByDpIdsV2(args.req,  function (err, result) {
      var result = new BizAccountPhoneInfoThriftService_getBizAccPhoneByDpIdsV2_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getBizAccPhoneByDpIdsV2", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountPhoneInfoThriftServiceProcessor.prototype.process_getBizAcctPhoneByIds = function(seqid, input, output) {
  var args = new BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getBizAcctPhoneByIds.length === 1) {
    Q.fcall(this._handler.getBizAcctPhoneByIds, args.req)
      .then(function(result) {
        var result = new BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result({success: result});
        output.writeMessageBegin("getBizAcctPhoneByIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result(err);
        output.writeMessageBegin("getBizAcctPhoneByIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getBizAcctPhoneByIds(args.req,  function (err, result) {
      var result = new BizAccountPhoneInfoThriftService_getBizAcctPhoneByIds_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getBizAcctPhoneByIds", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

