//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var CommonModel_ttypes = require('./CommonModel_types')
var BizAccountThirdThriftServiceModel_ttypes = require('./BizAccountThirdThriftServiceModel_types')


var ttypes = require('./BizAccountThirdThriftService_types');
//HELPER FUNCTIONS AND STRUCTURES

var BizAccountThirdThriftService_binding_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_binding_args.prototype = {};
BizAccountThirdThriftService_binding_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.BizAcctThirdBindingReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_binding_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_binding_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_binding_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_binding_result.prototype = {};
BizAccountThirdThriftService_binding_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.BizAcctThirdBindingResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_binding_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_binding_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_unBind_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_unBind_args.prototype = {};
BizAccountThirdThriftService_unBind_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.BizAcctThirdUnBindReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_unBind_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_unBind_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_unBind_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_unBind_result.prototype = {};
BizAccountThirdThriftService_unBind_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.BizAcctThirdUnBindResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_unBind_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_unBind_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getThirdBindingInfo_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_getThirdBindingInfo_args.prototype = {};
BizAccountThirdThriftService_getThirdBindingInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.BizAcctThirdBindingInfoReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getThirdBindingInfo_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getThirdBindingInfo_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getThirdBindingInfo_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_getThirdBindingInfo_result.prototype = {};
BizAccountThirdThriftService_getThirdBindingInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.BizAcctThirdInfoResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getThirdBindingInfo_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getThirdBindingInfo_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_saveThirdAcctInfo_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_saveThirdAcctInfo_args.prototype = {};
BizAccountThirdThriftService_saveThirdAcctInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.SaveThirdAcctInfoReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_saveThirdAcctInfo_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_saveThirdAcctInfo_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_saveThirdAcctInfo_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_saveThirdAcctInfo_result.prototype = {};
BizAccountThirdThriftService_saveThirdAcctInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.SaveThirdAcctInfoResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_saveThirdAcctInfo_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_saveThirdAcctInfo_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_follow_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_follow_args.prototype = {};
BizAccountThirdThriftService_follow_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_follow_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_follow_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_follow_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_follow_result.prototype = {};
BizAccountThirdThriftService_follow_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_follow_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_follow_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followV1_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_followV1_args.prototype = {};
BizAccountThirdThriftService_followV1_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowV1Req();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followV1_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followV1_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followV1_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_followV1_result.prototype = {};
BizAccountThirdThriftService_followV1_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followV1_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followV1_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followBinding_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_followBinding_args.prototype = {};
BizAccountThirdThriftService_followBinding_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowBindingReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followBinding_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followBinding_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followBinding_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_followBinding_result.prototype = {};
BizAccountThirdThriftService_followBinding_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followBinding_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followBinding_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followBindingV1_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_followBindingV1_args.prototype = {};
BizAccountThirdThriftService_followBindingV1_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowBindingV1Req();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followBindingV1_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followBindingV1_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followBindingV1_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_followBindingV1_result.prototype = {};
BizAccountThirdThriftService_followBindingV1_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followBindingV1_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followBindingV1_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_unFollow_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_unFollow_args.prototype = {};
BizAccountThirdThriftService_unFollow_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.WeChatUnFollowReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_unFollow_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_unFollow_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_unFollow_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_unFollow_result.prototype = {};
BizAccountThirdThriftService_unFollow_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.WeChatUnFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_unFollow_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_unFollow_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getWeChatInfoByAcctId_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_getWeChatInfoByAcctId_args.prototype = {};
BizAccountThirdThriftService_getWeChatInfoByAcctId_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.GetWeChatInfoReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getWeChatInfoByAcctId_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getWeChatInfoByAcctId_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getWeChatInfoByAcctId_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_getWeChatInfoByAcctId_result.prototype = {};
BizAccountThirdThriftService_getWeChatInfoByAcctId_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.GetWeChatInfoResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getWeChatInfoByAcctId_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getWeChatInfoByAcctId_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getWeChatInfoByAcctIds_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_getWeChatInfoByAcctIds_args.prototype = {};
BizAccountThirdThriftService_getWeChatInfoByAcctIds_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.req = new BizAccountThirdThriftServiceModel_ttypes.BatchGetWeChatInfoReq();
        this.req.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getWeChatInfoByAcctIds_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getWeChatInfoByAcctIds_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.STRUCT, 1);
    this.req.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getWeChatInfoByAcctIds_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_getWeChatInfoByAcctIds_result.prototype = {};
BizAccountThirdThriftService_getWeChatInfoByAcctIds_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.BatchGetWeChatInfoResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getWeChatInfoByAcctIds_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getWeChatInfoByAcctIds_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getWeChatInfoByOpenIds_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_getWeChatInfoByOpenIds_args.prototype = {};
BizAccountThirdThriftService_getWeChatInfoByOpenIds_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.SET) {
        var _size0 = 0;
        var _rtmp34;
        this.req = [];
        var _etype3 = 0;
        _rtmp34 = input.readSetBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = input.readString();
          this.req.push(elem6);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getWeChatInfoByOpenIds_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getWeChatInfoByOpenIds_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.SET, 1);
    output.writeSetBegin(Thrift.Type.STRING, this.req.length);
    for (var iter7 in this.req)
    {
      if (this.req.hasOwnProperty(iter7))
      {
        iter7 = this.req[iter7];
        output.writeString(iter7);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getWeChatInfoByOpenIds_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_getWeChatInfoByOpenIds_result.prototype = {};
BizAccountThirdThriftService_getWeChatInfoByOpenIds_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.BatchGetWeChatFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getWeChatInfoByOpenIds_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getWeChatInfoByOpenIds_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getWeChatInfoByUnionIds_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_getWeChatInfoByUnionIds_args.prototype = {};
BizAccountThirdThriftService_getWeChatInfoByUnionIds_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.SET) {
        var _size8 = 0;
        var _rtmp312;
        this.req = [];
        var _etype11 = 0;
        _rtmp312 = input.readSetBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = input.readString();
          this.req.push(elem14);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getWeChatInfoByUnionIds_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getWeChatInfoByUnionIds_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.SET, 1);
    output.writeSetBegin(Thrift.Type.STRING, this.req.length);
    for (var iter15 in this.req)
    {
      if (this.req.hasOwnProperty(iter15))
      {
        iter15 = this.req[iter15];
        output.writeString(iter15);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_getWeChatInfoByUnionIds_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_getWeChatInfoByUnionIds_result.prototype = {};
BizAccountThirdThriftService_getWeChatInfoByUnionIds_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.BatchGetWeChatFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_getWeChatInfoByUnionIds_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_getWeChatInfoByUnionIds_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followBindingImport_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_followBindingImport_args.prototype = {};
BizAccountThirdThriftService_followBindingImport_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size16 = 0;
        var _rtmp320;
        this.req = [];
        var _etype19 = 0;
        _rtmp320 = input.readListBegin();
        _etype19 = _rtmp320.etype;
        _size16 = _rtmp320.size;
        for (var _i21 = 0; _i21 < _size16; ++_i21)
        {
          var elem22 = null;
          elem22 = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowBindingImport();
          elem22.read(input);
          this.req.push(elem22);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followBindingImport_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followBindingImport_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRUCT, this.req.length);
    for (var iter23 in this.req)
    {
      if (this.req.hasOwnProperty(iter23))
      {
        iter23 = this.req[iter23];
        iter23.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followBindingImport_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_followBindingImport_result.prototype = {};
BizAccountThirdThriftService_followBindingImport_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followBindingImport_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followBindingImport_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followBindingImportV1_args = function(args) {
  this.req = null;
  if (args) {
    if (args.req !== undefined) {
      this.req = args.req;
    } else {
      throw new Thrift.TProtocolException(Thrift.TProtocolExceptionType.UNKNOWN, 'Required field req is unset!');
    }
  }
};
BizAccountThirdThriftService_followBindingImportV1_args.prototype = {};
BizAccountThirdThriftService_followBindingImportV1_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        var _size24 = 0;
        var _rtmp328;
        this.req = [];
        var _etype27 = 0;
        _rtmp328 = input.readListBegin();
        _etype27 = _rtmp328.etype;
        _size24 = _rtmp328.size;
        for (var _i29 = 0; _i29 < _size24; ++_i29)
        {
          var elem30 = null;
          elem30 = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowBindingImport();
          elem30.read(input);
          this.req.push(elem30);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followBindingImportV1_args.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followBindingImportV1_args');
  if (this.req !== null && this.req !== undefined) {
    output.writeFieldBegin('req', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRUCT, this.req.length);
    for (var iter31 in this.req)
    {
      if (this.req.hasOwnProperty(iter31))
      {
        iter31 = this.req[iter31];
        iter31.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftService_followBindingImportV1_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BizAccountThirdThriftService_followBindingImportV1_result.prototype = {};
BizAccountThirdThriftService_followBindingImportV1_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BizAccountThirdThriftServiceModel_ttypes.WeChatFollowResp();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BizAccountThirdThriftService_followBindingImportV1_result.prototype.write = function(output) {
  output.writeStructBegin('BizAccountThirdThriftService_followBindingImportV1_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BizAccountThirdThriftServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
BizAccountThirdThriftServiceClient.prototype = {};
BizAccountThirdThriftServiceClient.prototype.seqid = function() { return this._seqid; }
BizAccountThirdThriftServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
BizAccountThirdThriftServiceClient.prototype.binding = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_binding(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_binding(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_binding = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('binding', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_binding_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_binding = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_binding_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('binding failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.unBind = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_unBind(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_unBind(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_unBind = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('unBind', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_unBind_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_unBind = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_unBind_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('unBind failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.getThirdBindingInfo = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getThirdBindingInfo(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getThirdBindingInfo(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_getThirdBindingInfo = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getThirdBindingInfo', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_getThirdBindingInfo_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_getThirdBindingInfo = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_getThirdBindingInfo_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getThirdBindingInfo failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.saveThirdAcctInfo = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_saveThirdAcctInfo(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_saveThirdAcctInfo(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_saveThirdAcctInfo = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('saveThirdAcctInfo', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_saveThirdAcctInfo_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_saveThirdAcctInfo = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_saveThirdAcctInfo_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('saveThirdAcctInfo failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.follow = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_follow(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_follow(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_follow = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('follow', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_follow_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_follow = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_follow_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('follow failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.followV1 = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_followV1(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_followV1(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_followV1 = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('followV1', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_followV1_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_followV1 = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_followV1_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('followV1 failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.followBinding = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_followBinding(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_followBinding(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_followBinding = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('followBinding', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_followBinding_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_followBinding = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_followBinding_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('followBinding failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.followBindingV1 = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_followBindingV1(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_followBindingV1(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_followBindingV1 = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('followBindingV1', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_followBindingV1_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_followBindingV1 = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_followBindingV1_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('followBindingV1 failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.unFollow = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_unFollow(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_unFollow(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_unFollow = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('unFollow', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_unFollow_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_unFollow = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_unFollow_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('unFollow failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.getWeChatInfoByAcctId = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getWeChatInfoByAcctId(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getWeChatInfoByAcctId(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_getWeChatInfoByAcctId = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getWeChatInfoByAcctId', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_getWeChatInfoByAcctId_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_getWeChatInfoByAcctId = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_getWeChatInfoByAcctId_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getWeChatInfoByAcctId failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.getWeChatInfoByAcctIds = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getWeChatInfoByAcctIds(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getWeChatInfoByAcctIds(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_getWeChatInfoByAcctIds = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getWeChatInfoByAcctIds', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_getWeChatInfoByAcctIds_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_getWeChatInfoByAcctIds = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_getWeChatInfoByAcctIds_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getWeChatInfoByAcctIds failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.getWeChatInfoByOpenIds = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getWeChatInfoByOpenIds(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getWeChatInfoByOpenIds(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_getWeChatInfoByOpenIds = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getWeChatInfoByOpenIds', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_getWeChatInfoByOpenIds_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_getWeChatInfoByOpenIds = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_getWeChatInfoByOpenIds_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getWeChatInfoByOpenIds failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.getWeChatInfoByUnionIds = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getWeChatInfoByUnionIds(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getWeChatInfoByUnionIds(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_getWeChatInfoByUnionIds = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getWeChatInfoByUnionIds', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_getWeChatInfoByUnionIds_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_getWeChatInfoByUnionIds = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_getWeChatInfoByUnionIds_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getWeChatInfoByUnionIds failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.followBindingImport = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_followBindingImport(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_followBindingImport(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_followBindingImport = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('followBindingImport', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_followBindingImport_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_followBindingImport = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_followBindingImport_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('followBindingImport failed: unknown result');
};
BizAccountThirdThriftServiceClient.prototype.followBindingImportV1 = function(req, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_followBindingImportV1(req);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_followBindingImportV1(req);
  }
};

BizAccountThirdThriftServiceClient.prototype.send_followBindingImportV1 = function(req) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('followBindingImportV1', Thrift.MessageType.CALL, this.seqid());
  var args = new BizAccountThirdThriftService_followBindingImportV1_args();
  args.req = req;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BizAccountThirdThriftServiceClient.prototype.recv_followBindingImportV1 = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BizAccountThirdThriftService_followBindingImportV1_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('followBindingImportV1 failed: unknown result');
};
var BizAccountThirdThriftServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
BizAccountThirdThriftServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_binding = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_binding_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.binding.length === 1) {
    Q.fcall(this._handler.binding, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_binding_result({success: result});
        output.writeMessageBegin("binding", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_binding_result(err);
        output.writeMessageBegin("binding", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.binding(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_binding_result((err != null ? err : {success: result}));
      output.writeMessageBegin("binding", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_unBind = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_unBind_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.unBind.length === 1) {
    Q.fcall(this._handler.unBind, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_unBind_result({success: result});
        output.writeMessageBegin("unBind", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_unBind_result(err);
        output.writeMessageBegin("unBind", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.unBind(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_unBind_result((err != null ? err : {success: result}));
      output.writeMessageBegin("unBind", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_getThirdBindingInfo = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_getThirdBindingInfo_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getThirdBindingInfo.length === 1) {
    Q.fcall(this._handler.getThirdBindingInfo, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_getThirdBindingInfo_result({success: result});
        output.writeMessageBegin("getThirdBindingInfo", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_getThirdBindingInfo_result(err);
        output.writeMessageBegin("getThirdBindingInfo", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getThirdBindingInfo(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_getThirdBindingInfo_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getThirdBindingInfo", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_saveThirdAcctInfo = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_saveThirdAcctInfo_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.saveThirdAcctInfo.length === 1) {
    Q.fcall(this._handler.saveThirdAcctInfo, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_saveThirdAcctInfo_result({success: result});
        output.writeMessageBegin("saveThirdAcctInfo", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_saveThirdAcctInfo_result(err);
        output.writeMessageBegin("saveThirdAcctInfo", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.saveThirdAcctInfo(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_saveThirdAcctInfo_result((err != null ? err : {success: result}));
      output.writeMessageBegin("saveThirdAcctInfo", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_follow = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_follow_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.follow.length === 1) {
    Q.fcall(this._handler.follow, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_follow_result({success: result});
        output.writeMessageBegin("follow", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_follow_result(err);
        output.writeMessageBegin("follow", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.follow(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_follow_result((err != null ? err : {success: result}));
      output.writeMessageBegin("follow", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_followV1 = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_followV1_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.followV1.length === 1) {
    Q.fcall(this._handler.followV1, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_followV1_result({success: result});
        output.writeMessageBegin("followV1", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_followV1_result(err);
        output.writeMessageBegin("followV1", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.followV1(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_followV1_result((err != null ? err : {success: result}));
      output.writeMessageBegin("followV1", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_followBinding = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_followBinding_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.followBinding.length === 1) {
    Q.fcall(this._handler.followBinding, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_followBinding_result({success: result});
        output.writeMessageBegin("followBinding", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_followBinding_result(err);
        output.writeMessageBegin("followBinding", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.followBinding(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_followBinding_result((err != null ? err : {success: result}));
      output.writeMessageBegin("followBinding", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_followBindingV1 = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_followBindingV1_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.followBindingV1.length === 1) {
    Q.fcall(this._handler.followBindingV1, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_followBindingV1_result({success: result});
        output.writeMessageBegin("followBindingV1", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_followBindingV1_result(err);
        output.writeMessageBegin("followBindingV1", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.followBindingV1(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_followBindingV1_result((err != null ? err : {success: result}));
      output.writeMessageBegin("followBindingV1", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_unFollow = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_unFollow_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.unFollow.length === 1) {
    Q.fcall(this._handler.unFollow, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_unFollow_result({success: result});
        output.writeMessageBegin("unFollow", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_unFollow_result(err);
        output.writeMessageBegin("unFollow", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.unFollow(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_unFollow_result((err != null ? err : {success: result}));
      output.writeMessageBegin("unFollow", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_getWeChatInfoByAcctId = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_getWeChatInfoByAcctId_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getWeChatInfoByAcctId.length === 1) {
    Q.fcall(this._handler.getWeChatInfoByAcctId, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_getWeChatInfoByAcctId_result({success: result});
        output.writeMessageBegin("getWeChatInfoByAcctId", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_getWeChatInfoByAcctId_result(err);
        output.writeMessageBegin("getWeChatInfoByAcctId", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getWeChatInfoByAcctId(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_getWeChatInfoByAcctId_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getWeChatInfoByAcctId", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_getWeChatInfoByAcctIds = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_getWeChatInfoByAcctIds_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getWeChatInfoByAcctIds.length === 1) {
    Q.fcall(this._handler.getWeChatInfoByAcctIds, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_getWeChatInfoByAcctIds_result({success: result});
        output.writeMessageBegin("getWeChatInfoByAcctIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_getWeChatInfoByAcctIds_result(err);
        output.writeMessageBegin("getWeChatInfoByAcctIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getWeChatInfoByAcctIds(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_getWeChatInfoByAcctIds_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getWeChatInfoByAcctIds", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_getWeChatInfoByOpenIds = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_getWeChatInfoByOpenIds_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getWeChatInfoByOpenIds.length === 1) {
    Q.fcall(this._handler.getWeChatInfoByOpenIds, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_getWeChatInfoByOpenIds_result({success: result});
        output.writeMessageBegin("getWeChatInfoByOpenIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_getWeChatInfoByOpenIds_result(err);
        output.writeMessageBegin("getWeChatInfoByOpenIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getWeChatInfoByOpenIds(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_getWeChatInfoByOpenIds_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getWeChatInfoByOpenIds", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_getWeChatInfoByUnionIds = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_getWeChatInfoByUnionIds_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getWeChatInfoByUnionIds.length === 1) {
    Q.fcall(this._handler.getWeChatInfoByUnionIds, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_getWeChatInfoByUnionIds_result({success: result});
        output.writeMessageBegin("getWeChatInfoByUnionIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_getWeChatInfoByUnionIds_result(err);
        output.writeMessageBegin("getWeChatInfoByUnionIds", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getWeChatInfoByUnionIds(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_getWeChatInfoByUnionIds_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getWeChatInfoByUnionIds", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_followBindingImport = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_followBindingImport_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.followBindingImport.length === 1) {
    Q.fcall(this._handler.followBindingImport, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_followBindingImport_result({success: result});
        output.writeMessageBegin("followBindingImport", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_followBindingImport_result(err);
        output.writeMessageBegin("followBindingImport", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.followBindingImport(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_followBindingImport_result((err != null ? err : {success: result}));
      output.writeMessageBegin("followBindingImport", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

BizAccountThirdThriftServiceProcessor.prototype.process_followBindingImportV1 = function(seqid, input, output) {
  var args = new BizAccountThirdThriftService_followBindingImportV1_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.followBindingImportV1.length === 1) {
    Q.fcall(this._handler.followBindingImportV1, args.req)
      .then(function(result) {
        var result = new BizAccountThirdThriftService_followBindingImportV1_result({success: result});
        output.writeMessageBegin("followBindingImportV1", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new BizAccountThirdThriftService_followBindingImportV1_result(err);
        output.writeMessageBegin("followBindingImportV1", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.followBindingImportV1(args.req,  function (err, result) {
      var result = new BizAccountThirdThriftService_followBindingImportV1_result((err != null ? err : {success: result}));
      output.writeMessageBegin("followBindingImportV1", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

